Array:
	clang++ PointArray.cpp Array.cpp Point.cpp -Wall -pedantic -std=c++11 -g -o Arraymain.out

Heap:
	clang++ PointHeap.cpp Point.cpp -Wall -pedantic -std=c++11 -g -o Heap.out

PointMain:
	clang++ Pointmain.cpp Point.cpp -Wall -pedantic -std=c++11 -g -o PointMain.out

clean:
	rm -rf *.out
